/*
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.17.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * AddTimeOption options for adding time to an issue
 */
@ApiModel(description = "AddTimeOption options for adding time to an issue")

public class AddTimeOption {
  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("time")
  private Long time = null;

  @SerializedName("user_name")
  private String userName = null;

  public AddTimeOption created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public AddTimeOption time(Long time) {
    this.time = time;
    return this;
  }

   /**
   * time in seconds
   * @return time
  **/
  @ApiModelProperty(required = true, value = "time in seconds")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public AddTimeOption userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * User who spent the time (optional)
   * @return userName
  **/
  @ApiModelProperty(value = "User who spent the time (optional)")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddTimeOption addTimeOption = (AddTimeOption) o;
    return Objects.equals(this.created, addTimeOption.created) &&
        Objects.equals(this.time, addTimeOption.time) &&
        Objects.equals(this.userName, addTimeOption.userName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, time, userName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddTimeOption {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

