/*
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ChangedFile store information about files affected by the pull request
 */
@ApiModel(description = "ChangedFile store information about files affected by the pull request")

public class ChangedFile {
  @SerializedName("additions")
  private Long additions = null;

  @SerializedName("changes")
  private Long changes = null;

  @SerializedName("contents_url")
  private String contentsUrl = null;

  @SerializedName("deletions")
  private Long deletions = null;

  @SerializedName("filename")
  private String filename = null;

  @SerializedName("html_url")
  private String htmlUrl = null;

  @SerializedName("previous_filename")
  private String previousFilename = null;

  @SerializedName("raw_url")
  private String rawUrl = null;

  @SerializedName("status")
  private String status = null;

  public ChangedFile additions(Long additions) {
    this.additions = additions;
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  @ApiModelProperty(value = "")
  public Long getAdditions() {
    return additions;
  }

  public void setAdditions(Long additions) {
    this.additions = additions;
  }

  public ChangedFile changes(Long changes) {
    this.changes = changes;
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  @ApiModelProperty(value = "")
  public Long getChanges() {
    return changes;
  }

  public void setChanges(Long changes) {
    this.changes = changes;
  }

  public ChangedFile contentsUrl(String contentsUrl) {
    this.contentsUrl = contentsUrl;
    return this;
  }

   /**
   * Get contentsUrl
   * @return contentsUrl
  **/
  @ApiModelProperty(value = "")
  public String getContentsUrl() {
    return contentsUrl;
  }

  public void setContentsUrl(String contentsUrl) {
    this.contentsUrl = contentsUrl;
  }

  public ChangedFile deletions(Long deletions) {
    this.deletions = deletions;
    return this;
  }

   /**
   * Get deletions
   * @return deletions
  **/
  @ApiModelProperty(value = "")
  public Long getDeletions() {
    return deletions;
  }

  public void setDeletions(Long deletions) {
    this.deletions = deletions;
  }

  public ChangedFile filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @ApiModelProperty(value = "")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public ChangedFile htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  @ApiModelProperty(value = "")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public ChangedFile previousFilename(String previousFilename) {
    this.previousFilename = previousFilename;
    return this;
  }

   /**
   * Get previousFilename
   * @return previousFilename
  **/
  @ApiModelProperty(value = "")
  public String getPreviousFilename() {
    return previousFilename;
  }

  public void setPreviousFilename(String previousFilename) {
    this.previousFilename = previousFilename;
  }

  public ChangedFile rawUrl(String rawUrl) {
    this.rawUrl = rawUrl;
    return this;
  }

   /**
   * Get rawUrl
   * @return rawUrl
  **/
  @ApiModelProperty(value = "")
  public String getRawUrl() {
    return rawUrl;
  }

  public void setRawUrl(String rawUrl) {
    this.rawUrl = rawUrl;
  }

  public ChangedFile status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangedFile changedFile = (ChangedFile) o;
    return Objects.equals(this.additions, changedFile.additions) &&
        Objects.equals(this.changes, changedFile.changes) &&
        Objects.equals(this.contentsUrl, changedFile.contentsUrl) &&
        Objects.equals(this.deletions, changedFile.deletions) &&
        Objects.equals(this.filename, changedFile.filename) &&
        Objects.equals(this.htmlUrl, changedFile.htmlUrl) &&
        Objects.equals(this.previousFilename, changedFile.previousFilename) &&
        Objects.equals(this.rawUrl, changedFile.rawUrl) &&
        Objects.equals(this.status, changedFile.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additions, changes, contentsUrl, deletions, filename, htmlUrl, previousFilename, rawUrl, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangedFile {\n");
    
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    contentsUrl: ").append(toIndentedString(contentsUrl)).append("\n");
    sb.append("    deletions: ").append(toIndentedString(deletions)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    previousFilename: ").append(toIndentedString(previousFilename)).append("\n");
    sb.append("    rawUrl: ").append(toIndentedString(rawUrl)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

