/*
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.17.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CommitStats is statistics for a RepoCommit
 */
@ApiModel(description = "CommitStats is statistics for a RepoCommit")

public class CommitStats {
  @SerializedName("additions")
  private Long additions = null;

  @SerializedName("deletions")
  private Long deletions = null;

  @SerializedName("total")
  private Long total = null;

  public CommitStats additions(Long additions) {
    this.additions = additions;
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  @ApiModelProperty(value = "")
  public Long getAdditions() {
    return additions;
  }

  public void setAdditions(Long additions) {
    this.additions = additions;
  }

  public CommitStats deletions(Long deletions) {
    this.deletions = deletions;
    return this;
  }

   /**
   * Get deletions
   * @return deletions
  **/
  @ApiModelProperty(value = "")
  public Long getDeletions() {
    return deletions;
  }

  public void setDeletions(Long deletions) {
    this.deletions = deletions;
  }

  public CommitStats total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitStats commitStats = (CommitStats) o;
    return Objects.equals(this.additions, commitStats.additions) &&
        Objects.equals(this.deletions, commitStats.deletions) &&
        Objects.equals(this.total, commitStats.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additions, deletions, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitStats {\n");
    
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    deletions: ").append(toIndentedString(deletions)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

