/*
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.17.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateWikiPageOptions form for creating wiki
 */
@ApiModel(description = "CreateWikiPageOptions form for creating wiki")

public class CreateWikiPageOptions {
  @SerializedName("content_base64")
  private String contentBase64 = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("title")
  private String title = null;

  public CreateWikiPageOptions contentBase64(String contentBase64) {
    this.contentBase64 = contentBase64;
    return this;
  }

   /**
   * content must be base64 encoded
   * @return contentBase64
  **/
  @ApiModelProperty(value = "content must be base64 encoded")
  public String getContentBase64() {
    return contentBase64;
  }

  public void setContentBase64(String contentBase64) {
    this.contentBase64 = contentBase64;
  }

  public CreateWikiPageOptions message(String message) {
    this.message = message;
    return this;
  }

   /**
   * optional commit message summarizing the change
   * @return message
  **/
  @ApiModelProperty(value = "optional commit message summarizing the change")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public CreateWikiPageOptions title(String title) {
    this.title = title;
    return this;
  }

   /**
   * page title. leave empty to keep unchanged
   * @return title
  **/
  @ApiModelProperty(value = "page title. leave empty to keep unchanged")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWikiPageOptions createWikiPageOptions = (CreateWikiPageOptions) o;
    return Objects.equals(this.contentBase64, createWikiPageOptions.contentBase64) &&
        Objects.equals(this.message, createWikiPageOptions.message) &&
        Objects.equals(this.title, createWikiPageOptions.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentBase64, message, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWikiPageOptions {\n");
    
    sb.append("    contentBase64: ").append(toIndentedString(contentBase64)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

