/*
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NodeInfoUsageUsers contains statistics about the users of this server
 */
@ApiModel(description = "NodeInfoUsageUsers contains statistics about the users of this server")

public class NodeInfoUsageUsers {
  @SerializedName("activeHalfyear")
  private Long activeHalfyear = null;

  @SerializedName("activeMonth")
  private Long activeMonth = null;

  @SerializedName("total")
  private Long total = null;

  public NodeInfoUsageUsers activeHalfyear(Long activeHalfyear) {
    this.activeHalfyear = activeHalfyear;
    return this;
  }

   /**
   * Get activeHalfyear
   * @return activeHalfyear
  **/
  @ApiModelProperty(value = "")
  public Long getActiveHalfyear() {
    return activeHalfyear;
  }

  public void setActiveHalfyear(Long activeHalfyear) {
    this.activeHalfyear = activeHalfyear;
  }

  public NodeInfoUsageUsers activeMonth(Long activeMonth) {
    this.activeMonth = activeMonth;
    return this;
  }

   /**
   * Get activeMonth
   * @return activeMonth
  **/
  @ApiModelProperty(value = "")
  public Long getActiveMonth() {
    return activeMonth;
  }

  public void setActiveMonth(Long activeMonth) {
    this.activeMonth = activeMonth;
  }

  public NodeInfoUsageUsers total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeInfoUsageUsers nodeInfoUsageUsers = (NodeInfoUsageUsers) o;
    return Objects.equals(this.activeHalfyear, nodeInfoUsageUsers.activeHalfyear) &&
        Objects.equals(this.activeMonth, nodeInfoUsageUsers.activeMonth) &&
        Objects.equals(this.total, nodeInfoUsageUsers.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeHalfyear, activeMonth, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeInfoUsageUsers {\n");
    
    sb.append("    activeHalfyear: ").append(toIndentedString(activeHalfyear)).append("\n");
    sb.append("    activeMonth: ").append(toIndentedString(activeMonth)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

