/*
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.WikiCommit;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WikiCommitList commit/revision list
 */
@ApiModel(description = "WikiCommitList commit/revision list")

public class WikiCommitList {
  @SerializedName("commits")
  private List<WikiCommit> commits = null;

  @SerializedName("count")
  private Long count = null;

  public WikiCommitList commits(List<WikiCommit> commits) {
    this.commits = commits;
    return this;
  }

  public WikiCommitList addCommitsItem(WikiCommit commitsItem) {
    if (this.commits == null) {
      this.commits = new ArrayList<WikiCommit>();
    }
    this.commits.add(commitsItem);
    return this;
  }

   /**
   * Get commits
   * @return commits
  **/
  @ApiModelProperty(value = "")
  public List<WikiCommit> getCommits() {
    return commits;
  }

  public void setCommits(List<WikiCommit> commits) {
    this.commits = commits;
  }

  public WikiCommitList count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WikiCommitList wikiCommitList = (WikiCommitList) o;
    return Objects.equals(this.commits, wikiCommitList.commits) &&
        Objects.equals(this.count, wikiCommitList.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commits, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WikiCommitList {\n");
    
    sb.append("    commits: ").append(toIndentedString(commits)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

